variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version
  - dock container stop nginx-proxy

after_script:
  - cd ~/nginx/
  - docker-compose up -d


build:
  script: docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
    - docker container start webserver
  stage: deploy
  tags:
    - memento