variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version
  - docker-compose down --rmi all


build:
  script:
    - pwd
    - docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - memento