variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version
  - docker container stop webserver
  - docker container stop memento_client
  - docker volume rm memento_web-root


build:
  script: docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
    - docker container start webserver
  stage: deploy
  tags:
    - memento