variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version


build:
  script: docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up --build -d
    - docker restart nginx-proxy
  stage: deploy
  tags:
    - memento