variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version
  - docker-compose down
  - docker run --rm -v webroot:/srv/memento/ui/build busybox rm -rf '/srv/*'


build:
  script:
    - pwd
    - docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - memento