variables:
  GIT_CLONE_PATH: /home/sheku/

before_script:
  - docker version
  - docker-compose version



build:
  script:
    - docker exec nginx-proxy rm -rf /srv/memento/ui/build
    - docker-compose down --rmi all
    - docker-compose build --no-cache
  stage: build
  tags:
    - memento

deploy:
  script:
    - docker-compose up -d
  stage: deploy
  tags:
    - memento