version: '3.6'
volumes:
  webroot:
    name: webroot

networks:
  memento:
    external:
      name: memento

services:
  client:
    image: client:memento
    container_name: memento_client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - webroot:/srv/memento/ui/build
    networks:
      - memento