version: '3.6'
volumes:
  web-root:
    external: true
    name: memento_web-root

networks:
  memento:
    external:
      name: memento

services:

  client:
    image: client:memento
    container_name: memento_client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - web-root:/srv/memento/ui/build
    networks:
      - memento
