version: '3.6'
volumes:
  webroot:
    name: webroot

networks:
  memento:
    external:
      name: memento

services:

  client:
    image: client:memento
    container_name: memento_client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - web-root:/srv/memento/ui/build
    networks:
      - memento

  webserver:
    image: nginx-proxy:mainline-alpine
    container_name: memento_client_webserver
    restart: unless-stopped
    ports:
      - '8080:8080'
